# Generated by Django 4.2.5 on 2023-09-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdcutImages',
            new_name='ProdcutImage',
        ),
    ]
