# Generated by Django 4.2.5 on 2023-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_deliveries_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='product_id',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='product_id',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
