# Generated by Django 4.2.5 on 2023-11-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlist'),
        ('shop', '0009_alter_cart_user_id'),
    ]

    operations = [
    ]
