# Generated by Django 4.2.5 on 2023-11-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wishlist_id', models.IntegerField()),
                ('action_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=50)),
                ('new_value', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
