# Generated by Django 4.2.5 on 2023-11-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='shop/images')),
                ('side_image', models.ImageField(blank=True, default='', null=True, upload_to='shop/images')),
                ('back_image', models.ImageField(blank=True, default='', null=True, upload_to='shop/images')),
                ('front_image', models.ImageField(blank=True, default='', null=True, upload_to='shop/images')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
