# Generated by Django 4.2.5 on 2023-11-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_deliveries_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOffers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_price', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
