# Generated by Django 4.2.5 on 2023-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_product_id_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcutimage',
            name='back_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='prodcutimage',
            name='front_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='prodcutimage',
            name='side_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
